sonar.projectKey=AntaresSimulatorTeam_antares-datamanager-front
sonar.organization=antaressimulatorteam

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=antares-datamanager-front
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Tests with Vitest
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Coverage
sonar.coverage.exclusions=src/main.tsx, src/mocks/**,**/*.mock.ts, src/components/**, src/gitInfo.ts, src/pages/**, src/shared/const/**, src/types/**, src/**/*.type.ts

# Test coverage report
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
