/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/** @type {import('tailwindcss').Config} */

const bgImages = ['server-ok', 'server-ko', 'server-warn', 'update-notes'];

const bagroundImagridBasePath = '/background/imagrid/';
export default {
  darkMode: 'selector',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    { pattern: /bg-(server-(ok|ko|warn))/ },
    { pattern: /rotate-(0|1|2|3|6|45|90|180)/ },
    { pattern: /delay-(0|75|100|150|200|300|500|700|1000)/ },
    { pattern: /duration-(0|75|100|150|200|300|500|700|1000)/ },
    'bg-updates-notes',
    'max-h-14',
  ],
  theme: {
    screens: {
      sm: '1024px',
      md: '1280px',
      lg: '1440px',
      xl: '1680px',
      '2xl': '1920px',
      'aspect-narrow': { raw: '(max-aspect-ratio: 16/10)' },
      'aspect-medium': { raw: '(min-aspect-ratio: 16/10) and (max-aspect-ratio: 16/9)' },
      'aspect-wide': { raw: '(min-aspect-ratio: 16/9)' },
    },
    lineHeight: {
      s: '14px',
      m: '16px',
      l: '20px',
      xl: '24px',
      '2xl': '28px',
      '3xl': '32px',
      '4xl': '36px',
      '5xl': '40px',
      '6xl': '48px',
      '7xl': '56px',
      '8xl': '64px',
      '9xl': '80px',
      '10xl': '92px',
      4: '1rem',
    },
    letterSpacing: {
      none: '0px',
      s: '-0.5px',
      xs: '-1px',
    },
    fontWeight: {
      light: '300',
      regular: '400',
      semibold: '600',
      bold: '700',
    },
    colors: {
      // Base theme palettes (Light & Dark modes)
      greyscale: {
        0: '#f4f5f4',
        50: '#ebebea',
        100: '#e1e1e0',
        150: '#d7d6d5',
        200: '#cdcccb',
        250: '#c2c1c0',
        300: '#b7b7b6',
        350: '#acacab',
        400: '#a1a1a0',
        450: '#969695',
        500: '#8b8a8a',
        550: '#7f7e7e',
        600: '#737272',
        650: '#666665',
        700: '#595958',
        750: '#4c4c4b',
        800: '#3e3e3d',
        850: '#302f2f',
        900: '#201f1f',
        950: '#0d0c0c',
      },
      'bleu-iceberg': {
        0: '#f9fbfd',
        50: '#f3f6fc',
        100: '#e6eef8',
        200: '#c7dbf0',
        300: '#96bde3',
        400: '#5e9ad2',
        500: '#397ebe',
        600: '#2964a0',
        700: '#225082',
        800: '#214770',
        900: '#1f3b5b',
        950: '#15253c',
      },
      'vert-foret': {
        0: '#f5fcfa',
        50: '#effaf6',
        100: '#d7f4e6',
        200: '#b3e7d1',
        300: '#81d4b7',
        400: '#4dba97',
        500: '#2a9f7d',
        600: '#1b8065',
        700: '#176b57',
        800: '#145143',
        900: '#114338',
        950: '#082620',
      },
      violet: {
        0: '#fcfbfd',
        50: '#f9f7fc',
        100: '#f3eff8',
        200: '#e6def0',
        300: '#d2c3e4',
        400: '#b89fd3',
        500: '#9979bc',
        600: '#7d5a9f',
        700: '#674883',
        800: '#563c6c',
        900: '#4a355a',
        950: '#2b1a38',
      },

      // Design tokens mapping (Dynamic CSS variables defined by @design-system-rte themes)
      background: {
        default: 'var(--background-default)',
        hover: 'var(--background-hover)',
        disabled: 'var(--background-disabled)',
        inverse: 'var(--background-inverse)',
        'neutral-subtle-default': 'var(--background-neutral-subtle-default)',
        'neutral-subtle-hover': 'var(--background-neutral-subtle-hover)',
        'neutral-subtle-pressed': 'var(--background-neutral-subtle-pressed)',
        'neutral-regular-default': 'var(--background-neutral-regular-default)',
        'neutral-regular-hover': 'var(--background-neutral-regular-hover)',
        'neutral-regular-pressed': 'var(--background-neutral-regular-pressed)',
        'neutral-bold-default': 'var(--background-neutral-bold-default)',
        'neutral-bold-hover': 'var(--background-neutral-bold-hover)',
        'neutral-bold-pressed': 'var(--background-neutral-bold-pressed)',
        'neutral-navigation-default': 'var(--background-neutral-navigation-default)',
        'neutral-navigation-hover': 'var(--background-neutral-navigation-hover)',
        'brand-subtle-default': 'var(--background-brand-subtle-default)',
        'brand-subtle-hover': 'var(--background-brand-subtle-hover)',
        'brand-subtle-pressed': 'var(--background-brand-subtle-pressed)',
        'brand-default': 'var(--background-brand-default)',
        'brand-hover': 'var(--background-brand-hover)',
        'brand-pressed': 'var(--background-brand-pressed)',
        'brand-bold-default': 'var(--background-brand-bold-default)',
        'brand-bold-hover': 'var(--background-brand-bold-hover)',
        'brand-bold-pressed': 'var(--background-brand-bold-pressed)',
        'brand-selected-default': 'var(--background-brand-selected-default)',
        'brand-selected-hover': 'var(--background-brand-selected-hover)',
        'brand-unselected-default': 'var(--background-brand-unselected-default)',
        'brand-unselected-hover': 'var(--background-brand-unselected-hover)',
        'brand-inverse-default': 'var(--background-brand-inverse-default)',
        'brand-inverse-hover': 'var(--background-brand-inverse-hover)',
        'brand-inverse-pressed': 'var(--background-brand-inverse-pressed)',
        'brand-navigation-default': 'var(--background-brand-navigation-default)',
        'brand-navigation-hover': 'var(--background-brand-navigation-hover)',
        'brand-navigation-pressed': 'var(--background-brand-navigation-pressed)',
        'danger-default': 'var(--background-danger-default)',
        'danger-hover': 'var(--background-danger-hover)',
        'danger-pressed': 'var(--background-danger-pressed)',
        'info-default': 'var(--background-info-default)',
        'warning-default': 'var(--background-warning-default)',
        'success-default': 'var(--background-success-default)',
      },
      border: {
        primary: 'var(--border-primary)',
        secondary: 'var(--border-secondary)',
        tertiary: 'var(--border-tertiary)',
        divider: 'var(--border-divider)',
        disabled: 'var(--border-disabled)',
        inverse: 'var(--border-inverse)',
        'brand-default': 'var(--border-brand-default)',
        'brand-focused': 'var(--border-brand-focused)',
        'brand-navigation-active': 'var(--border-brand-navigation-active)',
        'brand-navigation-divider': 'var(--border-brand-navigation-divider)',
        danger: 'var(--border-danger)',
        info: 'var(--border-info)',
        warning: 'var(--border-warning)',
        success: 'var(--border-success)',
      },
      content: {
        primary: 'var(--content-primary)',
        secondary: 'var(--content-secondary)',
        tertiary: 'var(--content-tertiary)',
        'primary-inverse': 'var(--content-primary-inverse)',
        disabled: 'var(--content-disabled)',
        'brand-default': 'var(--content-brand-default)',
        'brand-hover': 'var(--content-brand-hover)',
        'brand-pressed': 'var(--content-brand-pressed)',
        'brand-navigation-default': 'var(--content-brand-navigation-default)',
        'brand-navigation-hover': 'var(--content-brand-navigation-hover)',
        'brand-navigation-disabled': 'var(--content-brand-navigation-disabled)',
        'link-default': 'var(--content-link-default)',
        'link-hover': 'var(--content-link-hover)',
        'link-pressed': 'var(--content-link-pressed)',
        'link-visited-default': 'var(--content-link-visited-default)',
        'link-visited-hover': 'var(--content-link-visited-hover)',
        'link-visited-pressed': 'var(--content-link-visited-pressed)',
        'danger-default': 'var(--content-danger-default)',
        'danger-hover': 'var(--content-danger-hover)',
        'danger-inverse': 'var(--content-danger-inverse)',
        'success-default': 'var(--content-success-default)',
        'success-hover': 'var(--content-success-hover)',
        'info-default': 'var(--content-info-default)',
        'info-hover': 'var(--content-info-hover)',
        decorative: 'var(--content-decorative)',
        static: 'var(--content-static)',
        'static-inverse': 'var(--content-static-inverse)',
      },
      status: {
        available: 'var(--status-available)',
        away: 'var(--status-away)',
        busy: 'var(--status-busy)',
        offline: 'var(--status-offline)',
        unknown: 'var(--status-unknown)',
      },
      chart: {
        brand: 'var(--chart-brand)',
        neutral: 'var(--chart-neutral)',
        'category-1': 'var(--chart-category-1)',
        'category-2': 'var(--chart-category-2)',
        'category-3': 'var(--chart-category-3)',
        'category-4': 'var(--chart-category-4)',
        'category-5': 'var(--chart-category-5)',
        'category-6': 'var(--chart-category-6)',
        'category-7': 'var(--chart-category-7)',
        'category-8': 'var(--chart-category-8)',
      },
      decorative: {
        neutral: 'var(--decorative-neutral)',
        'neutral-bold': 'var(--decorative-neutral-bold)',
        'bleu-iceberg': 'var(--decorative-bleu-iceberg)',
        'bleu-iceberg-bold': 'var(--decorative-bleu-iceberg-bold)',
        'vert-foret': 'var(--decorative-vert-foret)',
        'vert-foret-bold': 'var(--decorative-vert-foret-bold)',
        violet: 'var(--decorative-violet)',
        'violet-bold': 'var(--decorative-violet-bold)',
        'bleu-rte': 'var(--decorative-bleu-rte)',
        'bleu-rte-bold': 'var(--decorative-bleu-rte-bold)',
        'bleu-digital': 'var(--decorative-bleu-digital)',
        'bleu-digital-bold': 'var(--decorative-bleu-digital-bold)',
        marine: 'var(--decorative-marine)',
        'marine-bold': 'var(--decorative-marine-bold)',
        'bleu-petrole': 'var(--decorative-bleu-petrole)',
        'bleu-petrole-bold': 'var(--decorative-bleu-petrole-bold)',
        'bleu-cyan': 'var(--decorative-bleu-cyan)',
        'bleu-cyan-bold': 'var(--decorative-bleu-cyan-bold)',
        vert: 'var(--decorative-vert)',
        'vert-bold': 'var(--decorative-vert-bold)',
        'vert-indications': 'var(--decorative-vert-indications)',
        'vert-indications-bold': 'var(--decorative-vert-indications-bold)',
        'vert-digital': 'var(--decorative-vert-digital)',
        'vert-digital-bold': 'var(--decorative-vert-digital-bold)',
        jaune: 'var(--decorative-jaune)',
        'jaune-bold': 'var(--decorative-jaune-bold)',
        'jaune-ocre': 'var(--decorative-jaune-ocre)',
        'jaune-ocre-bold': 'var(--decorative-jaune-ocre-bold)',
        'jaune-indications': 'var(--decorative-jaune-indications)',
        'jaune-indications-bold': 'var(--decorative-jaune-indications-bold)',
        saumon: 'var(--decorative-saumon)',
        'saumon-bold': 'var(--decorative-saumon-bold)',
        'rose-digital': 'var(--decorative-rose-digital)',
        'rose-digital-bold': 'var(--decorative-rose-digital-bold)',
        fuschia: 'var(--decorative-fuschia)',
        'fuschia-bold': 'var(--decorative-fuschia-bold)',
        'rouge-indication': 'var(--decorative-rouge-indication)',
        'rouge-indication-bold': 'var(--decorative-rouge-indication-bold)',
        taupe: 'var(--decorative-taupe)',
        'taupe-bold': 'var(--decorative-taupe-bold)',
      },

      // Existing application aliases (for backward compatibility)
      primary: {
        50: '#effaf6',
        100: '#d7f4e6',
        200: '#b3e7d1',
        300: '#81d4b7',
        400: '#4dba97',
        500: '#2a9f7d',
        600: '#1b8065',
        700: '#176b57',
        800: '#145143',
        900: '#114338',
      },
      gray: {
        w: '#ffffff',
        50: '#f7f7f7',
        100: '#f2f4f4',
        200: '#eaeced',
        300: '#dddfe0',
        400: '#b7bec2',
        500: '#999fa1',
        600: '#6f767b',
        700: '#3b434a',
        800: '#292e33',
        900: '#11161a',
      },
      info: {
        50: '#eef7ff',
        100: '#d8ebff',
        200: '#baddff',
        300: '#8ac8ff',
        400: '#53aaff',
        500: '#2b86ff',
        600: '#1465fc',
        700: '#0d4fea',
        800: '#123fbb',
        900: '#153b93',
        950: '#122559',
      },
      error: {
        50: '#fff0f1',
        100: '#ffe5e7',
        200: '#ffccd1',
        300: '#ffa3ac',
        400: '#ff546a',
        500: '#ff3e5b',
        600: '#f71844',
        700: '#de0236',
        800: '#bd0536',
        900: '#a00836',
        950: '#630019',
      },
      success: {
        50: '#effef6',
        100: '#d9ffec',
        200: '#b5fdd9',
        300: '#65f8b0',
        400: '#3cec96',
        500: '#12d577',
        600: '#09b05f',
        700: '#0b8a4d',
        800: '#0e6d40',
        900: '#0e5937',
        950: '#01321c',
      },
      warning: {
        50: '#fef7eb',
        100: '#fce7c9',
        200: '#facf8e',
        300: '#f6ab4d',
        400: '#f8ab59',
        500: '#f38a3f',
        600: '#f36720',
        700: '#df4111',
        800: '#bc3115',
        900: '#a12c17',
        950: '#731807',
      },
      current: 'currentColor',
      transparent: 'transparent',
    },
    fontFamily: {
      nunito: ['Nunito', 'Nunito Sans Variable', 'sans-serif'],
      arial: ['Arial', 'sans-serif'],
      body: ['Nunito Sans Variable', 'Nunito', 'Arial', 'sans-serif'],
      sans: ['Nunito Sans Variable', 'Nunito', 'Arial', 'sans-serif'],
    },
    spacing: {
      0: '0px',
      0.125: '1px',
      0.25: '2px',
      0.5: '4px',
      0.75: '6px',
      1: '8px',
      1.25: '10px',
      1.5: '12px',
      1.75: '14px',
      2: '16px',
      2.25: '18px',
      2.5: '20px',
      3: '24px',
      4: '32px',
      5: '40px',
      6: '48px',
      7: '56px',
      8: '64px',
      9: '72px',
      10: '80px',
      11: '88px',
      12: '96px',
      13: '104px',
      14: '112px',
      15: '120px',
      16: '128px',
      18: '144px',
      20: '160px',
      22: '176px',
      24: '192px',
      28: '224px',
      32: '256px',
      64: '512px',
      120: '960px',
      168: '1344px',
      '25vw': '25vw',
      '30vw': '30vw',
      '35vw': '35vw',
      '40vw': '40vw',
      '45vw': '45vw',
      '55vw': '55vw',
      '60vw': '60vw',
      '65vw': '65vw',
      '70vw': '70vw',
      '75vw': '75vw',
      '80vw': '80vw',
      '90vw': '90vw',
      '95vw': '95vw',
      '98vw': '98vw',
      fit: 'fit-content',
    },
    fontSize: {
      // Primitives (_typography.scss)
      'font-s': ['10px', '14px'],
      'font-m': ['12px', '16px'],
      'font-l': ['14px', '20px'],
      'font-xl': ['16px', '24px'],
      'font-2xl': ['20px', '28px'],
      'font-3xl': ['24px', '32px'],
      'font-4xl': ['28px', '36px'],
      'font-5xl': ['32px', '40px'],
      'font-6xl': ['40px', '48px'],
      'font-7xl': ['48px', '56px'],
      'font-8xl': ['56px', '64px'],
      'font-9xl': ['68px', '80px'],
      'font-10xl': ['80px', '92px'],

      // Headings Design Tokens (_typography.scss)
      'heading-5xl': ['80px', { lineHeight: '92px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-4xl': ['68px', { lineHeight: '80px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-3xl': ['56px', { lineHeight: '64px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-2xl': ['48px', { lineHeight: '56px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-xl': ['40px', { lineHeight: '48px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-l': ['32px', { lineHeight: '40px', letterSpacing: '-1px', fontWeight: '600' }],
      'heading-m': ['24px', { lineHeight: '32px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'heading-s': ['20px', { lineHeight: '28px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'heading-xs': ['16px', { lineHeight: '24px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'heading-2xs': ['14px', { lineHeight: '20px', letterSpacing: '0px', fontWeight: '600' }],

      // Text / Body Design Tokens (_typography.scss)
      'body-xl': ['20px', { lineHeight: '28px', letterSpacing: '0px' }],
      'body-l': ['16px', { lineHeight: '24px', letterSpacing: '0px' }],
      'body-m': ['14px', { lineHeight: '20px', letterSpacing: '0px' }],
      'body-s': ['12px', { lineHeight: '16px', letterSpacing: '0px' }],
      'body-xs': ['10px', { lineHeight: '14px', letterSpacing: '0px' }],

      'text-xl': ['20px', { lineHeight: '28px', letterSpacing: '0px' }],
      'text-l': ['16px', { lineHeight: '24px', letterSpacing: '0px' }],
      'text-m': ['14px', { lineHeight: '20px', letterSpacing: '0px' }],
      'text-s': ['12px', { lineHeight: '16px', letterSpacing: '0px' }],
      'text-xs': ['10px', { lineHeight: '14px', letterSpacing: '0px' }],

      // Button Design Tokens (_typography.scss)
      'button-l': ['20px', { lineHeight: '28px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'button-m': ['16px', { lineHeight: '24px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'button-s': ['14px', { lineHeight: '20px', letterSpacing: '-0.5px', fontWeight: '600' }],
      'button-xs': ['12px', { lineHeight: '16px', letterSpacing: '0px' }],

      // Display & Legacy Aliases
      'display-xs': ['2rem', '2.4rem'],
      'display-s': ['2.25rem', '2.7rem'],
      'display-m': ['2.625rem', '3.15rem'],
      'display-l': ['3rem', '3.6rem'],
      'display-xl': ['3.375rem', '4.05rem'],
      caption: ['0.75rem', '0.75rem'],
      overnote: ['0.75rem', '0.875rem'],
    },
    boxShadow: {
      1: '0px 2px 6px 0px rgba(17, 22, 26, 0.08)',
      2: '0px 2px 6px 0px rgba(17, 22, 26, 0.16)',
      3: '0px 4px 24px 0px rgba(17, 22, 26, 0.20)',
      4: '0px 2px 6px 0px rgba(17, 22, 26, 0.16), 0px 4px 10px 0px rgba(17, 22, 26, 0.10)',
      5: '0px 2px 6px 0px rgba(17, 22, 26, 0.16), 0px 6px 16px 0px rgba(17, 22, 26, 0.20)',
      6: '0px 2px 6px 0px rgba(17, 22, 26, 0.16), 0px 6px 16px 0px rgba(17, 22, 26, 0.20), 0px 16px 16px 0px rgba(17, 22, 26, 0.12)',
      7: '0px 2px 6px 0px rgba(0, 0, 0, 0.16), 0px 10px 20px 0px rgba(17, 22, 26, 0.20), 0px 24px 24px 0px rgba(17, 22, 26, 0.12)',
      'switch-unchecked-small': '1px 0px 1px 0px rgba(153, 159, 161, 0.10)',
      'switch-checked-small': '-1px 0px 1px 0px rgba(0, 156, 223, 0.10)',
      'switch-unchecked-medium': '1.5px 0px 1.5px 0px rgba(153, 159, 161, 0.10)',
      'switch-checked-medium': '-1.5px 0px 1.5px 0px rgba(0, 156, 223, 0.10)',
    },
    backgroundImage: Object.fromEntries(bgImages.map((item) => [item, `url("${bagroundImagridBasePath}${item}.svg")`])),
    gridTemplateRows: {
      'home-layout': '32px 144px',
    },
    extend: {
      minWidth: {
        '3': '1.5rem',
        '1/2': '50%',
      },
      maxWidth: {
        168: '1344px',
        32: '256px',
      },
      maxHeight: {
        14: '112px',
      },
      gridTemplateRows: {
        'progress-bar-rows': '20px 8px 22px',
      },
      gridTemplateColumns: {
        'progress-bar-columns': '100px 16px 32px',
      },
      transitionProperty: {
        height: 'height',
      },
    },
  },
  plugins: [],
};
