export enum STUDY_ACTION {
  ADD_TRAJECTORY_AREA = 'ADD_TRAJECTORY_AREA',
  ADD_TRAJECTORY_LINK = 'ADD_TRAJECTORY_LINK',
  SET_STUDY_STATUS = 'SET_STUDY_STATUS',
  CLEAR_AREA_TRAJECTORY = 'CLEAR_AREA_TRAJECTORY',
  CLEAR_LINK_TRAJECTORY = 'CLEAR_LINK_TRAJECTORY',
  CLEAR_AREA_AND_LINK = 'CLEAR_AREA_AND_LINK',
  ADD_TRAJECTORIES = 'ADD_TRAJECTORIES',
}
