export enum STUDY_ACTION {
  CLEAR_TRAJECTORY_BY_TYPE = 'CLEAR_TRAJECTORY_BY_TYPE',
  SET_STUDY_STATUS = 'SET_STUDY_STATUS',
  ADD_TRAJECTORIES = 'ADD_TRAJECTORIES',
  ADD_WARNING_MESSAGES = 'ADD_WARNING_MESSAGES',
  SKIP_MESSAGE = 'SKIP_MESSAGE',
  DELETE_TRAJECTORY = 'DELETE_TRAJECTORY',
  UPDATE_TRAJECTORY = 'UPDATE_TRAJECTORY',
  RESET_STUDY_STATE = 'RESET_STUDY_STATE',
  SET_STUDY_AREAS = 'SET_STUDY_AREAS',
}
