export enum STUDY_ACTION {
  ADD_TRAJECTORY_AREA = 'ADD_TRAJECTORY_AREA',
  ADD_TRAJECTORY_LINK = 'ADD_TRAJECTORY_LINK',
  CLEAR_AREA_LINK_TRAJECTORY = 'CLEAR_AREA_LINK_TRAJECTORY',
  SET_IS_STUDY_GENERATED = 'SET_IS_STUDY_GENERATED',
  CLEAR_LINK_TRAJECTORY = 'CLEAR_LINK_TRAJECTORY',
  ADD_TRAJECTORIES = 'ADD_TRAJECTORIES',
}
