export enum WARNING_MESSAGE_LEVEL {
  WARNING_LEVEL = 'WARNING_LEVEL',
  ERROR_LEVEL = 'ERROR_LEVEL',
  INFO_LEVEL = 'INFO_LEVEL',
  FATAL_LEVEL = 'FATAL_LEVEL',
}

export enum ERROR_MESSAGE_TYPE {
  BUSINESS = 'BUSINESS',
  TECHNICAL = 'TECHNICAL',
}
