import { TRAJECTORY_TYPE } from '@/shared/enum/trajectory.ts';

export const THERMAL_TYPES = [
  TRAJECTORY_TYPE.THERMAL_TECHNICAL_SPECIFIC_PARAMETER,
  TRAJECTORY_TYPE.THERMAL_TECHNICAL_COMMON_PARAMETER,
  TRAJECTORY_TYPE.THERMAL_TECHNICAL_MODULATION_PARAMETER,
];
